version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aromacafe_api
    ports:
      - "5035:8080"
    depends_on:
      - mysql
      - elasticsearch
    environment:

      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Port=3306;Database=aromacafedb;User=root;Password=123456;"
      Elasticsearch__Uri: "http://elasticsearch:9200"
      Jwt__Key: "AromaCafe_Jwt_Secret_Key_2026_Super_Safe_123456"
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    container_name: aromacafe_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: aromacafedb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: aromacafe_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - appnet

volumes:
  mysql_data:
  es_data:

networks:
  appnet: